# Generated by Django 4.0.4 on 2022-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=200)),
                ('printer_status', models.CharField(max_length=50)),
                ('t0_temp_actual', models.CharField(max_length=20)),
                ('t0_temp_set', models.CharField(max_length=20)),
                ('bed_temp_actual', models.CharField(max_length=20)),
                ('bed_temp_set', models.CharField(max_length=20)),
                ('progress', models.CharField(max_length=20)),
            ],
        ),
    ]
